apiVersion: v1
kind: Pod # poderia usa o deployment
metadata:
  name: myapp-php
spec:
  containers:
  - name: myapp-php
    image: sandrosa0315/myapp-php:1.0
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-php-service
spec:
  type: NodePort
  selector:
    app: myapp-php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005 # Precisa ser acima de 30000